import 'package:flutter/material.dart';

class SavedToken{
  static const String token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvcXVhbWFnZHkyNUBnbWFpbC5jb20iLCJwaG9uZSI6IisyMDEyMzQ1Njc4OTAiLCJpZCI6IjY2ZTlkMGViMTJkMzljMDFhNDdjNmViMCIsImlhdCI6MTcyNjgzNzc2NiwiZXhwIjoxNzM3MjA1NzY2fQ.nqnDC6-IaQLdeqDdKL3avzu0sU_EXEk_zfiMvUoXX-E';
}
